Random word gen
jraffile/JavaBookClub pull request #5
Opened 2016-09-28 17:14 UTC by ccampbell08

this code is dope

2016-09-28 17:38 UTC, blandflakes requested changes

2016-09-28 17:38 UTC, blandflakes commented on Dictionary.txt
> +1briansucks
This is bullshit

2016-09-28 17:38 UTC, blandflakes commented on HangMan.java
> +//hi dudes
Remove useless comment

2016-09-28 17:38 UTC, blandflakes commented on RandomWordGen.java
> +        try(Stream<String> lines = Files.lines(Paths.get("/Users/Zeus/Documents/JavaBookClub/Dictionary.txt"))){
I'd recommend removing the leading numbers and putting each word in an ArrayList<String>. Then just generating a random number between 0 (inclusive) and the length of the list (exclusive) can be used to select and item from the list.

2016-09-28 17:46 UTC, blandflakes commented on RandomWordGen.java
> +        try(Stream<String> lines = Files.lines(Paths.get("/Users/Zeus/Documents/JavaBookClub/Dictionary.txt"))){
To get the lines from a file, you can use Files.readAllLines (from @christopher-brady)

2018-05-30 15:04 UTC, closed without merging

2018-06-07 20:04 UTC, ccampbell08 commented on Dictionary.txt
> +1briansucks
@blandflakes 
Lol, sorry about this

2018-06-07 20:05 UTC, blandflakes commented
All of my pull requests start with "1briansucks"

On Thu, Jun 7, 2018 at 4:04 PM Christopher Campbell <
notifications@github.com> wrote:

> *@ccampbell08* commented on this pull request.
> ------------------------------
>
> In Dictionary.txt
> <https://github.com/jraffile/JavaBookClub/pull/5#discussion_r193872886>:
>
> > @@ -0,0 +1,10 @@
> +0bigpoops
> +1briansucks
>
> @blandflakes <https://github.com/blandflakes>
> Lol, sorry about this
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/jraffile/JavaBookClub/pull/5#discussion_r193872886>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAFhhNHFe1gcJqOn_ax_t7zobGnvw5Bzks5t6Yc-gaJpZM4KJFGD>
> .
>